steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'RerunTests.sln'

- task: VSBuild@1
  inputs:
    solution: 'RerunTests.sln'
    platform: 'Any CPU'
    configuration: 'Release'

- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\*Tests*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    runInParallel: true
    codeCoverageEnabled: true
    diagnosticsEnabled: false
    rerunFailedTests: true
